spring:
    application:
        name: jobtrigger
    jackson:
        serialization:
            INDENT_OUTPUT: true
server:
    context-path: /jobtrigger
    port: 8080
edison:
    gracefulshutdown:
        enabled: false
    jobtrigger:
        jobresults:
            max: 1000
        scheduler:
            poolsize: 10
    metrics:
        slf4j:
            logger: de.otto.edison.jobtrigger
    status:
        redirect-internal:
            enabled: true
endpoints:
    metrics:
        filter:
            enabled: false
management:
    contextPath: /internal
    health:
        diskspace:
            enabled: false


