spring:
    application:
        name: jobtrigger
    jackson:
        serialization:
        INDENT_OUTPUT: true
    thymeleaf:
        mode: HTML5

server:
    context-path: /jobtrigger
    port: 8080

aws:
    profile:

base:
    url: https://${service.name}.${GROUP:develop}.${service.vertical}.cloud.otto.de

togglz:
    s3:
        enabled: false
        bucketName: someTogglzBucketName

edison:
    aws:
        config:
            s3:
                enabled: false
                bucketname: someBucketName
            paramstore:
                enabled: false
                path: /${service.vertical}/${service.name}
    ldap:
        enabled: false
    gracefulshutdown:
        enabled: false
    jobtrigger:
        jobresults:
            max: 1000
        scheduler:
            poolsize: 10
        security:
            basicAuthUser: someUser
            basicAuthPasswd: somePassword
    status:
          redirect-internal:
              enabled: true

endpoints:
    metrics:
        filter:
            enabled: false

management:
    context-path: /internal
    security:
        enabled: false
